import {
  applyTransformers,
  convertBooleanToBit,
  convertLargeInsertStatementsToSqlServer,
  convertIdentifierQuotesToSqlServer,
  convertILikeToLike,
  convertLimitToTop,
  convertNowToGetDate,
  convertPostgresArrayDefaultsToSqlServer,
  convertPostgresDataTypesToSqlServer,
  convertPostgresEnumTypesToSqlServer,
  convertIndexedMaxTextColumnsToSqlServer,
  convertPostgresIndexesToSqlServer,
  convertPostgresTimestampLiteralsToSqlServer,
  convertPostgresUuidDefaultsToSqlServer,
  convertPublicSchemaQualifierToSqlServer,
  convertInlineForeignKeysToSqlServer,
  convertReferencesToSqlServer,
  convertSerialToIdentity,
  convertSqlServerCreateTablesToIfNotExists,
  convertSqlServerOffsetDefaults,
  convertUpdatedAtTriggerToSqlServer,
  wrapSqlServerInsertScriptsWithConstraintHandling,
  removePostgresTablespaceClauses,
  removePostgresTypeCasts
} from '../shared/transformers.js';

export function postgresToSqlServer(query) {
  return applyTransformers(
    query,
    convertIdentifierQuotesToSqlServer,
    convertPostgresEnumTypesToSqlServer,
    removePostgresTypeCasts,
    convertPostgresDataTypesToSqlServer,
    convertPostgresUuidDefaultsToSqlServer,
    convertPostgresArrayDefaultsToSqlServer,
    convertPostgresIndexesToSqlServer,
    convertUpdatedAtTriggerToSqlServer,
    convertPublicSchemaQualifierToSqlServer,
    convertReferencesToSqlServer,
    removePostgresTablespaceClauses,
    convertInlineForeignKeysToSqlServer,
    convertIndexedMaxTextColumnsToSqlServer,
    convertSerialToIdentity,
    convertBooleanToBit,
    convertNowToGetDate,
    convertSqlServerOffsetDefaults,
    convertPostgresTimestampLiteralsToSqlServer,
    convertSqlServerCreateTablesToIfNotExists,
    convertLargeInsertStatementsToSqlServer,
    wrapSqlServerInsertScriptsWithConstraintHandling,
    convertILikeToLike,
    convertLimitToTop
  );
}
